# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gifThanks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gifThanks
  pod 'Google/SignIn'

  target 'gifThanks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gifThanksTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gifThanks-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
